This script show that $\frac{\partial}{\partial A}\mathrm{Tr} P = U$, where $A = UP$ is polar decompostion. 

In [50]:
import numpy as np
from scipy.linalg import polar

dx = 1e-7 # perturbation
i, j = 0, 0 # entity location

a = np.random.randn(4,4)
print(a)

b = np.copy(a)
b[i][j] = a[i][j] + dx # add perturbation on one entity
print(b)

[[-0.66183144 -0.08472254  0.81659021 -0.94025356]
 [-0.48487801  0.89701372 -0.52531008 -1.01026165]
 [-0.50036886 -0.79846795  0.46921244  2.08268852]
 [-0.45394071 -0.49700556  0.2428076  -0.87267715]]
[[-0.66183134 -0.08472254  0.81659021 -0.94025356]
 [-0.48487801  0.89701372 -0.52531008 -1.01026165]
 [-0.50036886 -0.79846795  0.46921244  2.08268852]
 [-0.45394071 -0.49700556  0.2428076  -0.87267715]]


In [51]:
au, ap = polar(a)
bu, bp = polar(b)
print(bp - ap)

# very close result...
print(np.trace(bp - ap) / dx) # not right definition
print((np.trace(bp)-np.trace(ap))/dx)
print(au[i][j])

[[-5.06753495e-08 -1.91040878e-10  3.73428761e-08 -2.54860746e-08]
 [-1.91040822e-10  3.40534489e-10  2.73866152e-10  3.95317556e-10]
 [ 3.73428761e-08  2.73866152e-10  1.27497867e-08 -4.10513555e-09]
 [-2.54860745e-08  3.95317556e-10 -4.10513556e-09  1.71970749e-09]]
-0.35865320824335356
-0.35865324045508995
